### PR TITLE
LIBTD-1339: Customize Collection metadata including modeling, forms, …

### PR DESCRIPTION
**Pull request by tingtingjh**
…views; upgrade to Hyrax 2.1.0 to fix show collection error

Label coverage metadata as Location

### CODE REVIEW

**Comment by shabububu** [comment]
I have a general comment. Instead of copying large classes directly from the Hyrax Gem to override, consider using `prepend`.  For example, the collections form and presenters have a lot of duplicate code from the Gem. Using `prepend` instead could potentially make future upgrades easier, if later versions of Hyrax have code changes that occur outside of the functionality that you're looking to override. It also makes it clearer what exactly is being overridden from the gem.

* An example prepend to override a CollectionsController is here:
https://github.com/VTUL/iawa/blob/LIBTD-1256/config/application.rb#L34
* Corresponding module with code to override gem functionality:
https://github.com/VTUL/iawa/blob/LIBTD-1256/app/controllers/hyrax/collections_controller_override.rb

Edit: Overall, it looks fine. This is just a style suggestion.

**Comment by shabububu** [comment]
I was able to bring up the application, log in, create a collection type, and create a new collection. The form fields match the previous iawa application as expected. Both the dashboard and "public" view of	the collection display the expected fields compared to the Hyrax 1.0.4 version	of the application. Everything looks as I would expect.

**Review by shabububu — APPROVED** [review]
I've added my comments above. Everything looks fine. I have one suggestion, and it's more of a style decision. I approve.

**Comment by tingtingjh** [comment]
Good point. I will change as you suggested.

**Comment by tingtingjh** [comment]
@shabububu I have changed to use prepend to override the form and presenter. Please take a look.

**Review by shabububu — APPROVED** [review]
I looked at the updated changes, and they look good to me.

**Pull request merged**
